// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lassoc
List lassoc(const arma::mat& XX, const arma::mat& XY, const arma::mat& initB, const arma::mat& ind, const double lam, std::string crit, const double tol, const double maxit);
RcppExport SEXP _GLASSOO_lassoc(SEXP XXSEXP, SEXP XYSEXP, SEXP initBSEXP, SEXP indSEXP, SEXP lamSEXP, SEXP critSEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type XX(XXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XY(XYSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type initB(initBSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ind(indSEXP);
    Rcpp::traits::input_parameter< const double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< std::string >::type crit(critSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(lassoc(XX, XY, initB, ind, lam, crit, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GLASSOO_lassoc", (DL_FUNC) &_GLASSOO_lassoc, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_GLASSOO(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
