// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// CV_GLASSOc
List CV_GLASSOc(const arma::mat& X, const arma::mat& S, const arma::colvec& lam, bool diagonal, bool path, std::string crit_out, std::string crit_in, const double tol_out, const double tol_in, int maxit_out, int maxit_in, int adjmaxit_out, int K, std::string crit_cv, std::string start, std::string trace);
RcppExport SEXP _GLASSOO_CV_GLASSOc(SEXP XSEXP, SEXP SSEXP, SEXP lamSEXP, SEXP diagonalSEXP, SEXP pathSEXP, SEXP crit_outSEXP, SEXP crit_inSEXP, SEXP tol_outSEXP, SEXP tol_inSEXP, SEXP maxit_outSEXP, SEXP maxit_inSEXP, SEXP adjmaxit_outSEXP, SEXP KSEXP, SEXP crit_cvSEXP, SEXP startSEXP, SEXP traceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< bool >::type diagonal(diagonalSEXP);
    Rcpp::traits::input_parameter< bool >::type path(pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type crit_out(crit_outSEXP);
    Rcpp::traits::input_parameter< std::string >::type crit_in(crit_inSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_out(tol_outSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_in(tol_inSEXP);
    Rcpp::traits::input_parameter< int >::type maxit_out(maxit_outSEXP);
    Rcpp::traits::input_parameter< int >::type maxit_in(maxit_inSEXP);
    Rcpp::traits::input_parameter< int >::type adjmaxit_out(adjmaxit_outSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< std::string >::type crit_cv(crit_cvSEXP);
    Rcpp::traits::input_parameter< std::string >::type start(startSEXP);
    Rcpp::traits::input_parameter< std::string >::type trace(traceSEXP);
    rcpp_result_gen = Rcpp::wrap(CV_GLASSOc(X, S, lam, diagonal, path, crit_out, crit_in, tol_out, tol_in, maxit_out, maxit_in, adjmaxit_out, K, crit_cv, start, trace));
    return rcpp_result_gen;
END_RCPP
}
// CVP_GLASSOc
arma::mat CVP_GLASSOc(const int n, const arma::mat& S_train, const arma::mat& S_valid, const arma::colvec& lam, bool diagonal, std::string crit_out, std::string crit_in, const double tol_out, const double tol_in, int maxit_out, int maxit_in, int adjmaxit_out, std::string crit_cv, std::string start, std::string trace);
RcppExport SEXP _GLASSOO_CVP_GLASSOc(SEXP nSEXP, SEXP S_trainSEXP, SEXP S_validSEXP, SEXP lamSEXP, SEXP diagonalSEXP, SEXP crit_outSEXP, SEXP crit_inSEXP, SEXP tol_outSEXP, SEXP tol_inSEXP, SEXP maxit_outSEXP, SEXP maxit_inSEXP, SEXP adjmaxit_outSEXP, SEXP crit_cvSEXP, SEXP startSEXP, SEXP traceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S_train(S_trainSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type S_valid(S_validSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< bool >::type diagonal(diagonalSEXP);
    Rcpp::traits::input_parameter< std::string >::type crit_out(crit_outSEXP);
    Rcpp::traits::input_parameter< std::string >::type crit_in(crit_inSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_out(tol_outSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_in(tol_inSEXP);
    Rcpp::traits::input_parameter< int >::type maxit_out(maxit_outSEXP);
    Rcpp::traits::input_parameter< int >::type maxit_in(maxit_inSEXP);
    Rcpp::traits::input_parameter< int >::type adjmaxit_out(adjmaxit_outSEXP);
    Rcpp::traits::input_parameter< std::string >::type crit_cv(crit_cvSEXP);
    Rcpp::traits::input_parameter< std::string >::type start(startSEXP);
    Rcpp::traits::input_parameter< std::string >::type trace(traceSEXP);
    rcpp_result_gen = Rcpp::wrap(CVP_GLASSOc(n, S_train, S_valid, lam, diagonal, crit_out, crit_in, tol_out, tol_in, maxit_out, maxit_in, adjmaxit_out, crit_cv, start, trace));
    return rcpp_result_gen;
END_RCPP
}
// GLASSOc
List GLASSOc(const arma::mat& S, const arma::mat& initSigma, const arma::mat& initOmega, const double lam, std::string crit_out, std::string crit_in, const double tol_out, const double tol_in, const int maxit_out, const int maxit_in);
RcppExport SEXP _GLASSOO_GLASSOc(SEXP SSEXP, SEXP initSigmaSEXP, SEXP initOmegaSEXP, SEXP lamSEXP, SEXP crit_outSEXP, SEXP crit_inSEXP, SEXP tol_outSEXP, SEXP tol_inSEXP, SEXP maxit_outSEXP, SEXP maxit_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type S(SSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type initSigma(initSigmaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type initOmega(initOmegaSEXP);
    Rcpp::traits::input_parameter< const double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< std::string >::type crit_out(crit_outSEXP);
    Rcpp::traits::input_parameter< std::string >::type crit_in(crit_inSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_out(tol_outSEXP);
    Rcpp::traits::input_parameter< const double >::type tol_in(tol_inSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit_out(maxit_outSEXP);
    Rcpp::traits::input_parameter< const int >::type maxit_in(maxit_inSEXP);
    rcpp_result_gen = Rcpp::wrap(GLASSOc(S, initSigma, initOmega, lam, crit_out, crit_in, tol_out, tol_in, maxit_out, maxit_in));
    return rcpp_result_gen;
END_RCPP
}
// lassoc
List lassoc(const arma::mat& XX, const arma::mat& XY, const arma::mat& initB, const arma::mat& initH, const arma::mat& ind, const double lam, std::string crit, const double tol, const double maxit);
RcppExport SEXP _GLASSOO_lassoc(SEXP XXSEXP, SEXP XYSEXP, SEXP initBSEXP, SEXP initHSEXP, SEXP indSEXP, SEXP lamSEXP, SEXP critSEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type XX(XXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XY(XYSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type initB(initBSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type initH(initHSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ind(indSEXP);
    Rcpp::traits::input_parameter< const double >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< std::string >::type crit(critSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(lassoc(XX, XY, initB, initH, ind, lam, crit, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GLASSOO_CV_GLASSOc", (DL_FUNC) &_GLASSOO_CV_GLASSOc, 16},
    {"_GLASSOO_CVP_GLASSOc", (DL_FUNC) &_GLASSOO_CVP_GLASSOc, 15},
    {"_GLASSOO_GLASSOc", (DL_FUNC) &_GLASSOO_GLASSOc, 10},
    {"_GLASSOO_lassoc", (DL_FUNC) &_GLASSOO_lassoc, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_GLASSOO(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
